# Generated by Django 4.1.5 on 2023-01-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupon',
            new_name='Coupon',
        ),
    ]
